- name: Configure users
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    path: /etc/ssh/sshd_config
    backup: yes
    validate: "/usr/sbin/sshd -T -f %s"
    content: |
      Match User {{ item.name }}
        #AllowTcpForwarding yes
        #X11Forwarding no
        #PermitTunnel no
        #GatewayPorts no
        AllowAgentForwarding no
        ForceCommand echo 'This account can only be used for reversed ssh'
        PermitOpen 127.0.0.1:{{ item.port }}
  become: true

- name: Add users
  user:
    name: "{{ item.name }}"
    shell: /bin/false
    group: restricted-ssh
  become: true

- name: Create ssh folder
  file:
    path: "/home/{{ item.name }}/.ssh"
    mode: 0700
    state: directory
    group: restricted-ssh
    owner: "{{ item.name }}"
  become: true

- name: Create authorized_keys
  file:
    path: "/home/{{ item.name }}/.ssh/authorized_keys"
    mode: 0600
    state: touch
    group: restricted-ssh
    owner: "{{ item.name }}"
  become: true
