- name: Install SSH client config
  blockinfile:
    create: yes
    path: "/home/{{ ansible_user }}/.ssh/config"
    content: |
      Host reverse-ssh
        Hostname {{ public_ip }}
        User {{ remote_user }}
        Port {{ remote_port }}
        IdentityFile ~/.ssh/client-reverse-ssh
        ServerAliveInterval 30
        ServerAliveCountMax 3
        RemoteForward {{ port }} localhost:{{ port }}

- name: Install autossh
  apt:
    name: autossh
    update_cache: yes
  become: true

- name: Copy autossh service
  template:
    src: autossh-service.j2
    dest: /etc/systemd/system/autossh.service
  become: true

- name: Enable and start autossh service
  systemd: 
    state: started
    name: autossh
    daemon_reload: yes
    enabled: yes
  become: true
